# Generated by Django 5.2.12 on 2026-03-07 23:36

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(default='CA', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(max_length=64)),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='parcel_app.jurisdiction')),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apn', models.CharField(db_index=True, help_text='Assessor Parcel Number', max_length=64)),
                ('address', models.TextField(blank=True, null=True)),
                ('owner_name', models.TextField(blank=True, null=True)),
                ('lot_size_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('land_use_code', models.CharField(blank=True, max_length=64, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('source_crs', models.CharField(blank=True, max_length=64, null=True)),
                ('data_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='parcel_app.jurisdiction')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='parcel_app.source')),
            ],
            options={
                'indexes': [models.Index(fields=['apn'], name='parcel_app__apn_1da4e6_idx')],
                'unique_together': {('source', 'apn')},
            },
        ),
    ]
