# Generated by Django 5.2.12 on 2026-03-10 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('zoning_code', 'Zoning Code'), ('ordinance', 'Ordinance'), ('plan', 'Plan'), ('other', 'Other')], default='other', max_length=32)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='parcel_app.jurisdiction')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='parcel_app.source')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extractor_name', models.CharField(max_length=128)),
                ('model_name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=32)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_runs', to='parcel_app.document')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('setback', 'Setback'), ('height_limit', 'Height Limit'), ('lot_coverage', 'Lot Coverage'), ('other', 'Other')], default='other', max_length=32)),
                ('value_text', models.TextField()),
                ('unit', models.CharField(blank=True, max_length=32, null=True)),
                ('applies_to', models.CharField(blank=True, max_length=255, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('citation_text', models.TextField()),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_rules', to='parcel_app.document')),
                ('extraction_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_rules', to='parcel_app.extractionrun')),
            ],
        ),
    ]
