# Generated by Django 5.2.12 on 2026-03-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_app', '0002_document_extractionrun_extractedrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionrun',
            name='raw_response_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
