# Generated by Django 5.2.12 on 2026-03-11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parcel_app", "0003_extractionrun_raw_response_text"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ExtractedRule",
            new_name="ExtractedConstraint",
        ),
        migrations.AlterField(
            model_name="extractedconstraint",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extracted_constraints",
                to="parcel_app.document",
            ),
        ),
        migrations.AlterField(
            model_name="extractedconstraint",
            name="extraction_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extracted_constraints",
                to="parcel_app.extractionrun",
            ),
        ),
    ]
