# Generated by Django 5.2.12 on 2026-03-11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parcel_app", "0004_rename_extractedrule_extractedconstraint"),
    ]

    operations = [
        migrations.RenameField(
            model_name="extractedconstraint",
            old_name="rule_type",
            new_name="constraint_type",
        ),
    ]
